### PR TITLE
Allow autoloading of class nested into another class (not only into module)

### PR DESCRIPTION
**Pull request by akoltun**
Added additional check into private __autoload method. If there is a file with the same name as the directory then autoload this file instead of creating a module.

Also tests added.

### CODE REVIEW

**Comment by jarmo** [comment]
Is this PR still relevant? Closing it for now, but if it is still relevant then let me know and I'll look into it.

**Comment by akoltun** [comment]
Yes, it is still relevant. Please, take a look into it

**Comment by jarmo** [comment]
Reopened.

**Comment by jarmo** [comment]
Merged and released version 1.5.0. Thanks!

**Pull request merged**
