### PR TITLE
Removing MIT references

### PR DESCRIPTION
**Pull request by enkessler**
I saw that you don't consider the project to use the MIT license so I went ahead and updated some places that still said that it did.

Updating the license might still be a good idea, though.

### CODE REVIEW

**Comment by jarmo** [comment]
Thanks!

**Comment by enkessler** [comment]
@jarmo Looking at the history of the project, it looks likes there's the 5 committers tracked by GitHub plus Tony (I didn't go through every commit and check for other untracked committers). And because you and I are already fine with MIT, it doesn't sound insurmountable to get the input of all committers now before the list grows anymore. Additionally, looking at the earliest commits in the project, Tony added all of the MIT references at the same time that he added the non-MIT license. So, arguably, the project was meant to be MIT (he was calling it that) even though the license and what it was called never matched.

What do you think?

**Comment by jarmo** [comment]
As I said - I don't have anything against MIT and would prefer it to current one. If you have time to contact all of the contributors and get an approval then go for it. I'm currently busy with other projects and can't promise anything :(

**Comment by enkessler** [comment]
@jarmo I'm on it. :)

**Pull request merged**
